In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from train import get_data, encode_dataset,split_scale_data
from sklearn.ensemble import RandomForestClassifier

In [7]:
import pandas as pd
import joblib

In [13]:
data = get_data()
encode_data, encoder = encode_dataset(data)

In [14]:
encode_data.head()

,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
0,0,54,1,1,26,23,0.20,0,31,0,1
1,2,33,2,0,141,62,0.34,2,0,1,0
2,1,38,0,2,199,38,0.04,1,0,1,1
3,0,22,1,3,36,2,0.31,1,0,1,0
4,2,29,7,0,250,57,0.36,1,0,1,1

In [16]:
X_train, X_test, y_train, y_test = split_scale_data(data=encode_data)

In [20]:
y_train.shape

(6400,)

In [22]:
data.head()

,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
0,0,54,1,1,26,23,0.20,0,31,0,1
1,2,33,2,0,141,62,0.34,2,0,1,0
2,1,38,0,2,199,38,0.04,1,0,1,1
3,0,22,1,3,36,2,0.31,1,0,1,0
4,2,29,7,0,250,57,0.36,1,0,1,1

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   gender                 8000 non-null   int64
 1   age                    8000 non-null   int64
 2   country                8000 non-null   int64
 3   subscription_type      8000 non-null   int64
 4   listening_time         8000 non-null   int64
 5   songs_played_per_day   8000 non-null   int64
 6   skip_rate              8000 non-null   float64
 7   device_type            8000 non-null   int64
 8   ads_listened_per_week  8000 non-null   int64
 9   offline_listening      8000 non-null   int64
 10  is_churned             8000 non-null   int64
dtypes: float64(1), int64(10)
memory usage: 687.6 KB

In [37]:
data_zero = data[data['is_churned'] == 0].iloc[0:2071]
data_one = data[data['is_churned'] == 1]

data = pd.concat([data_zero, data_one])
data.reset_index(drop=True, inplace=True)




X = data.drop(columns=["is_churned"])
y = data['is_churned']

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


categorical_cols = data.select_dtypes(include="object").columns
for col in categorical_cols:
    encoder = LabelEncoder()
    data[col] = encoder.fit_transform(data[col])
    

X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=23,test_size=0.5,
                                                    stratify=y)

In [39]:
scaler = StandardScaler()
column_names = X_train.columns
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

X_train = pd.DataFrame(data=X_train, columns = column_names)
X_test = pd.DataFrame(data=X_test, columns = column_names)

In [42]:
model = RandomForestClassifier(random_state=23, n_estimators=5)
from sklearn.metrics import f1_score


model.fit(X_train, y_train)
train_preds = model.predict(X_train)
test_preds = model.predict(X_test)

print(f1_score(y_train, train_preds))
print(f1_score(y_test, test_preds))

0.9477250726040658
0.4927675988428158

In [38]:
data['is_churned'].value_counts()

is_churned
0    2071
1    2071
Name: count, dtype: int64